<div class='container' class='m-3 p-3'>
<form action="../user/submit">
    <h1 class="text-center">Add User</h1>
    <label for="">Name</label>
    <input type="text" class="form-control" name='name'>
    <br>
    <label for="">email</label>
    <input type="text" class="form-control" name='email'>
    <br>
    <label for="">Password</label>
    <input type="text" class="form-control" name='pswd'>
    <br>
    <input type="submit" value="Submit" class='btn btn-primary'>
</form>
</div>
