<div class='container' class='m-3 p-3'>
    <form action="product/submit">
        <h1 class="text-center">Add Product</h1>
        <label for="">Name</label>
        <input type="text" class="form-control" name='name'>
        <br>
        <label for="">catageory</label>
        <input type="text" class="form-control" name='catageory'>
        <br>
        <label for="">price</label>
        <input type="text" class="form-control" name='price'>
        <br>
        <label for="">Quantity</label>
        <input type="text" class="form-control" name='qty'>
        <br>
        <input type="submit" value="Submit" class='btn btn-primary'>
    </form>
</div>
