<table class="table table-bordered table-striped">
    <caption>Product details</caption>
    <thead>
        <th>id</th>
        <th>name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>desc</th>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $value) {
            echo "<tr><td>" . $value['id']['$oid'] . "</td><td>$value[name]</td><td>$value[price]</td><td>
            $value[qty]</td><td>$value[desc]</td></tr>";
        }
        ?>
    </tbody>
</table>
